export const LANG_EN_NAME = 'en';
export const LANG_EN_SKOD = 2;

export const LANG_EN_TRANS = {
    /*LOGIN*/
    'Welcome to BRAVO+': 'Welcome to BRAVO+',
    'Username': 'Username',
    'Password': 'Password',
    'Login': 'Login',
    'Language': 'Language',
    'Forgot password?': 'Forgot password?',
    'Do not have an account?': 'Do not have an account?',
    'Create an account': 'Create an account',
    'INCORRECT_USERNAME_PASSWORD': 'Incorrect username or password',
    /*PRODUCT OVERVIEW*/
    'Product Overview': 'Product Overview',
    'Name': 'Name',
    'ArticleGroup': 'Product Group',
    'Search': 'Search',
    'Search article': 'Search product',
    'Select article': 'Select product',
    /*PRODUCT DETAILS*/
    'Product Details': 'Product Details',
    'Full Name': 'Full Name',
    'Price': 'Price',
    'Price In': 'Price In',
    'Price Cost': 'Price Cost',
    'Product': 'Product',
    'Save changes': 'Save changes',
    'SAVE_ARTICLE_SUCCESSFULLY': 'The article has been saved OK.',
    'SAVE_ARTICLE_FAILED': 'Save article failed.',

    // Customer
    'Search customers': 'Search customers',
    'id': 'Id',
    'address': 'Address',
    'name': 'Name',
    'zip code': 'Zip code',
    'zipName': 'City',
    'alfa': 'Alfa',
    'company address': 'Company Address',
    'postal code': 'Postal Code',
    'country': 'Country',
    'org number': 'Org. Number',
    'fax': 'Fax',
    'fax 2': 'Fax 2',
    'email': 'Email',
    'private phone': 'Private Phone',
    'mobile phone': 'Mobile Phone',
    'website': 'Website',
    'email company': 'Email Company',
    'email invoice': 'Email Invoice',
    'save': 'Save',
    'add': 'Add',
    'telephoneWork': 'Work Phone',
    'contact': 'Contact',
    'Customer Detail': 'Customer Detail',
    'Customer Overview': 'Customer Overview',
    'Details': 'Details',
    'Stock': 'Stock',
    'back': 'Back',
    'cancel': 'Cancel',
    /*PRODUCT STOCK*/
    'Select Warehouse': 'Select Warehouse',
    'TotalStock': 'Total stock',
    'Physical': 'Physical',
    'Reserved': 'Reserved',
    'Rested': 'Rested',
    'OnHand': 'On Hand',
    'Ordered': 'Ordered',
    'Disposable': 'Disposable',
    'OnHandWithOrdered': 'On Hand With Ordered',
    'delete success': 'Data has been deleted OK.',
    'save success': 'Data has been saved OK.',
    /*ORDER OVERVIEW*/
    'Order Overview': 'Order Overview',
    'Find orders': 'Find Orders',

    /*ORDER DETAIL*/
    'Offer': 'Offer',
    'Order': 'Order',
    'Reference': 'Reference',
    'Delivery': 'Delivery',
    'Order Details': 'Order',
    'Address': 'Address',
    'Company Address': 'Company Address',
    'PAddress': 'PAddress',
    'OrderNo': 'Order number',
    'Order type': 'Order type',
    'Order Discount': 'Order Discount',
    'Order Value': 'Order Value',
    'Customer no.': 'Customer no',
    'Email': 'Email',
    'Telephone': 'Telephone',
    'Mobile': 'Mobile',
    'SaleNo': 'Seller',
    'Our reference': 'Our reference',
    'Order Reference': 'Order Reference',
    'Their reference': 'Your reference',
    'Delivery Address': 'Delivery Address',
    'DeliveryDate': 'Delivery date',
    'Delivery method': 'Delivery method',
    'Order Text': 'Order Text',
    'Order detail': 'Order detail',
    'OrderType': 'Order Type',
    'OrderStatus': 'Order Status',
    'OrderDate': 'Order Date',
    'Customer': 'Customer',
    'CustomerNo': 'Customer No',
    'SAVE_ORDER_SUCCESSFULLY': 'The order has been saved OK.',
    'SAVE_ORDER_FAILED': 'Save order failed.',
    'Lines': 'Lines',
    'MISSING_INFORMATION': 'Please input required information',
    /*Forgot Password*/
    'reset password': 'Reset Password',
    'home': 'Home',
    // BreadCrum
    'customer': 'Customer',
    'order': 'Order',
    'detail': 'Detail',
    'Add Customer': 'Add Customer',
    'Edit Customer': 'Edit Customer',
    'Add Product': 'Add Product',
    'Edit Product': 'Edit Product',

    //left menu
    'Customer Card': 'Customer Card',
    'EButikk': 'Netshop',
    'EShop orders': 'Netshop orders',
    'Booking Confirmation': 'Booking Confirmation',

    /*Item List*/
    'Item List': 'Item List',
    'hideItemsWithoutInventory': 'Hide Items Without Inventory',
    'ArticleNumber': 'Article Number',

    // Setting
    'Edit Permission': 'Edit Permission',
    'settings': 'Settings',
    'Load permission successfully': 'Load permission successfully',
    'Reload Permission': 'Reload Permission',
    'Edit Mode': 'Edit Mode',
    'Review': 'Review',
    'Export Excel': 'Export to Excel',

    'Nr.': 'Number',
    'Nanv': 'Customer Name',
    'Besøksadresse': 'Address',
    'Postadresse': 'Mail address',
    'Postnummer': 'Zip code',
    'Poststed': 'City',
    'Print': 'Print',

    /*INVOICE OVERVIEW*/
    'Find invoices': 'Find invoices',
    'InvoiceNo': 'InvoiceNo.',
    'InvoiceType': 'Invoice Type',
    'InvoiceDate': 'Invoice Date',
    'InvoiceStatus': 'Invoice Status',
    'Status': 'Status',
    'PostNo/place': 'Zip/City',
    'Date': 'Date',
    'DueDate': 'Due Date',
    'OurRef': 'Our ref.',
    'TheirRef': 'Your ref.',
    'UtleggStatus': 'Utl.sts',
    'Sum': 'Sum',
    'CustomerName': 'CustomerName',

    /*INVOICE DETAILS*/
    'Show Invoice Details': 'Show Invoice Details',
    'LineNo': 'LineNo.',
    'ProductWorth': 'Product Value',
    'RoundingAmount': 'Rounding amount',
    'Freight': 'Freight',
    'InvoiceFee': 'Invoice Fee',
    'SumAddition': 'Total Addition',
    'CustomerNo-Name': 'CustNo/Name',
    'VisitingAddress': 'Visiting Address',
    'PostAddress': 'Postal Address',

    'SAVE_INVOICE_FAILED': 'Save Invoice Failed',

    'New': 'New',
    'Loading': 'Loading',

    /*ORDER DETAILS LINE*/
    'ArticleNo': 'Product No',
    'Text': 'Text',
    'Quantity': 'Quantity',
    'LinePrice': 'Line Price',
    'LineText': 'Line Text',
    'SAVE_ORDER_LINE_SUCCESSFULLY': 'Line has been saved OK.',
    'SAVE_ORDER_LINE_FAILED': 'Save line failed.',
    // Structure
    'Width': 'Width',
    'Height': 'Height',
    'Hello': 'Hello',
    'Close': 'Close'
};
