export const LANG_NB_NAME = 'nb';

export const LANG_NB_SKOD = 1;

export const LANG_NB_TRANS = {
  /*LOGIN*/
  'Welcome to BRAVO+': 'Velkommen til BRAVO PLUSS',
  'Username': 'Brukernavn',
  'Password': 'Passord',
  'Login': 'Logg Inn',
  'Language': 'Språk',
  'Forgot password?': 'Glemt passord?',
  'Do not have an account?': 'Ingen konto?',
  'Create an account': 'Opprett en konto',
  'INCORRECT_USERNAME_PASSWORD': 'Feil brukernavn eller passord',
  /*PRODUCT OVERVIEW*/
  'Product Overview': 'Produktoversikt',
  'Name': 'Navn',
  'ArticleGroup': 'Produktgruppe',
  'Search': 'Søk',
  'Search article': 'Søk produkt',
  'Select article': 'Velg produkt',
  /*PRODUCT DETAILS*/
  'Product Details': 'Produkt-detaljer',
  'Full Name': 'Full beskrivelse',
  'Price': 'Pris',
  'Price In': 'Innpris',
  'Price Cost': 'Kostpris',
  'Product': 'Produkt',
  'Save changes': 'Lagre endringer',
  'SAVE_ARTICLE_SUCCESSFULLY': 'Lagre artikkel OK',
  'SAVE_ARTICLE_FAILED': 'Lagre produkt feilet',

  // Customer
  'Search customers': 'Søk kunde',
  'id': 'Nr.',
  'address': 'Postadresse',
  'name': 'Navn',
  'zip code': 'Postnummer',
  'zipName': 'Poststed',
  'alfa': 'Alfa',
  'company address': 'Besøksadresse',
  'postal code': 'Postnr./-sted',
  'country': 'Land',
  'org number': 'Org.nummer',
  'fax': 'Telefaks ',
  'fax 2': 'Telefaks 2',
  'email': 'E-post',
  'private phone': 'Telefon privat',
  'mobile phone': 'Mobiltelefon',
  'website': 'Webside ',
  'email company': 'Firmapost',
  'email invoice': 'E-post faktura',
  'save': 'Lagre',
  'add': 'Legg til',
  'telephoneWork': 'Telefon arbeid',
  'contact': 'Kontakt',
  'Customer Detail': 'Kundekort',
  'Customer Overview': 'Kundeoversikt',
  'Details': 'Detaljer',
  'Stock': 'Lager',
  'back': 'Tilbake',
  'cancel': 'Avbryt',
  /*PRODUCT STOCK*/
  'Select Warehouse': 'Velg lager',
  'TotalStock': 'Total lagerbeholdning',
  'Physical': 'Fysisk',
  'Reserved': 'Reservert',
  'Rested': 'Restet',
  'OnHand': 'Disp',
  'Ordered': 'Bestilt',
  'Disposable': 'Disponibel',
  'OnHandWithOrdered': 'Disp2',
  'delete success': 'Slett OK',
  'save success': 'Lagre OK',
  /*ORDER OVERVIEW*/
  'Order Overview': 'Ordre-oversikt',
  'Find orders': 'Finn ordrer',
  /*ORDER DDETAIL*/
  'Offer': 'Tilbud',
  'Order': 'Ordre',
  'Reference': 'Referanse',
  'Delivery': 'Leverings',
  'Order Details': 'Ordre',
  'Address': 'Adresse',
  'Company Address': 'Co.adresse',
  'PAddress': 'P.address',
  'OrderNo': 'Ordrenr',
  'Order type': 'Ordretype',
  'Order Discount': 'Ordrerabatt',
  'Order Value': 'Ordreverdi',
  'Customer no': 'Kundenr.',
  'Email': 'Epost',
  'Telephone': 'Telefon',
  'Mobile': 'Mobil',
  'SaleNo': 'Selger',
  'Our reference': 'Vår referanse',
  'Order Reference': 'Ordre referanse',
  'Their reference': 'Deres referanse',
  'Delivery Address': 'Leveringsadresse',
  'DeliveryDate': 'Leverings dato',
  'Delivery method': 'Leverings måte',
  'Order Text': 'Ordretekst',
  'Order detail': 'Ordre detaljer',
  'OrderType': 'Ordretype',
  'OrderStatus': 'Ordrestatus',
  'OrderDate': 'Ordredato',
  'Customer': 'Kunde',
  'CustomerNo': 'Kunde nr',
  'SAVE_ORDER_SUCCESSFULLY': 'Lagre ordre OK',
  'SAVE_ORDER_FAILED': 'Lagre ordre feilet',
  'Lines': 'Linjer',
  'MISSING_INFORMATION': 'Vennligst skriv inn nødvendig informasjon',
  /*Forgot Password*/
  'reset password': 'Tilbakestille passord',
  // Breadcrum
  'home': 'Hjem',
  'customer': 'Kunde',
  'product': 'Produkt',
  'order': 'Ordre',
  'detail': 'Detalj',
  'Add Customer': 'Legg til kunde',
  'Edit Customer': 'Rediger kunde',
  'Add Product': 'Legg til produkt',
  'Edit Product': 'Rediger produkt',

  //left menu
  'Customer Card': 'Kundekort',
  'EButikk': 'eButikk',
  'EShop orders': 'e-butikk bestillinger',
  'Booking Confirmation': 'Bestillingsbekreftelse',

  /*Item List*/
  'Item List': 'Vareliste',
  'hideItemsWithoutInventory': 'Skjul varer uten beholdning',
  'ArticleNumber': 'Produktnummer',

  // Setting
  'Edit Permission': 'Rediger tillatelse',
  'settings': 'Innstillinger',
  'Load permission successfully': 'Last inn tillatelse OK',
  'Reload Permission': 'Last inn tillatelse',
  'Edit Mode': 'Redigeringsmodus',
  'Review': 'Anmeldelse',
  'Export Excel': 'Åpne i Excel',

  'Nr.': 'Nr.',
  'Besøksadresse': 'Besøksadresse',
  'Nanv': 'Nanv',
  'Postadresse': 'Postadresse',
  'Postnummer': 'Postnummer',
  'Poststed': 'Poststed',
  'Print': 'Skriv ut',

  /*INVOICE OVERVIEW*/
  'Find invoices': 'Finn fakturaer',
  'InvoiceNo': 'Fakturanr.',
  'InvoiceType': 'Fakturatype',
  'InvoiceDate': 'Fakturadato',
  'InvoiceStatus': 'Faktura Status',
  'Status': 'Status',
  'PostNo/place': 'Postnr/-sted',
  'Date': 'Dato',
  'DueDate': 'Forfall',
  'OurRef': 'Vår ref.',
  'TheirRef': 'Deres ref.',
  'UtleggStatus': 'Utl.sts',
  'Sum': 'Sum',
  'CustomerName': 'Kundenavn',

  /*INVOICE DETAILS*/
  'Show Invoice Details': 'Vis utgående faktura',
  'LineNo': 'Linjenr.',
  'ProductWorth': 'Vareverdi',
  'RoundingAmount': 'Avrundet',
  'Freight': 'Frakt',
  'InvoiceFee': 'Fakturaavgift',
  'SumAddition': 'Sum tillegg',
  'CustomerNo-Name': 'Kundenr./-navn',
  'VisitingAddress': 'Besøksadresse',
  'PostAddress': 'Postadresse',

  'SAVE_INVOICE_FAILED': 'Lagre faktura feilet',

  'New': 'Ny',
  'Loading': 'Laster',

  /*ORDER DETAILS LINE*/
  'ArticleNo': 'Prod.nr.',
  'Text': 'Tekst',
  'Quantity': 'Antall',
  'LinePrice': 'Linjepris',
  'LineText': 'Linjetekst',
  'SAVE_ORDER_LINE_SUCCESSFULLY': 'Linjen har blitt lagret.',
  'SAVE_ORDER_LINE_FAILED': 'Lagre linjen feilet.',
  // Structure
  'Width': 'Bredde',
  'Height': 'Høyde',
  'Hello': 'Hallo',
  'Close': 'Lukk'
};
